title: GeoInvention 数据集
description: "一个支持 Markdown 自动生成的数据集平台"
baseurl: "" # 如果你在子路径发布，比如 /repo-name，则写 "/repo-name"
url: "https://你的用户名.github.io" # GitHub Pages 地址

# theme: minima

collections:
  datasets:
    output: true
    permalink: /datasets/:name/

defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
